ACTIVE_PROFILE: dev
DB_HOST: localhost
DB_PORT: 5432
DB_NAME: bank
DB_USER: bank
DB_URL : jdbc:postgresql://localhost:5432/bank
DB_SCHEMA: bank
DB_PASSWORD: bank123


PORT: 8000
CONTAINER_PORT: 8000
devUrl: http://localhost:8080
prodUrl: ""

