name: mini bank deployment

on:
  push:
    branches: [production]
    paths:
      - 'src/**'
      - '.github/workflows/prod.yml'

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Build project
        run: mvn clean install -DskipTests
      - name: Login to Docker
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t abayomexy/banky .
      - name: Publish image to docker hub
        run: docker push abayomexy/banky

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull abayomexy/banky:latest
      - name: Delete Old containers
        run: sudo docker rm -f banky
      - name: Run docker container
        run: sudo docker run -d -p 8000:8000 -e CONTAINER_PORT=${{secrets.CONTAINER_PORT}} -e DB_URL=${{secrets.DB_URL}} -e DB_PASSWORD=${{secrets.DB_PASSWORD}} --name abayomexy/banky
